version: '3.3'
services:
  mcp-api:
    restart: unless-stopped
    build: .
    container_name: mcp-api
    volumes:
#      - "./:/app:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - type: bind
        source: ./
        target: /app
    environment:
      VIRTUAL_HOST: "mcp.kurohai.com"
      VIRTUAL_PORT: "8087"
      # VIRTUAL_ROOT: "/"
      HTTPS_METHOD: "redirect"
      HSTS: "off"
      LETSENCRYPT_HOST: "mcp.kurohai.com"
      LETSENCRYPT_EMAIL: "kurohai@gmail.com"
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 8087
      FLASK_DEBUG: 1
      FLASK_APP: mcp.wsgi:app
      FLASK_ENV: development

    ports:
      - published: 8087
        target: 8087

networks:
  default:
    external:
      name: mcp-net
